### ISSUE TITLE
Define release cycle of registry docker image

### ISSUE THREAD

**Issue by ruflin** [elastic/package-registry#122]
The official registry will always be run of the `:latest` tag (or similar) to make sure all newest packages are contained. But there should also be an option to pull the docker image multiple time and make sure it has the same content. For this we need some release tags for the docker images. Some ideas so far:

* Weekly releases (2019-{weeknumber})
* Release with the Elastic Stack

**Comment by ruflin** [comment]
In https://github.com/elastic/package-registry/issues/375 a discussion is started on how to name each Docker image. I'm now wondering if for release we could use certain tags as the release mechanism. For example if we want to make `202004231234-c890763-c1d2c2c` available on staging we tag this image also with `staging`. As soon as the `staging` tag changes, the container is redeployed. The above would be the release mechanism. 

In general, I would like to release as frequent as possible to get new packages out to the user immediately. As soon as a new package is pushed to the package storage, it should be made available: https://github.com/elastic/package-storage The risk of this is that with the continous deployment we can't test every version. So instead to start with we can start with weekly releases but with the goal of having continuous automated releases. The weekly releases would be manually at first.

I would already like to start testing the continous releases on our staging environment. This means every time a new container shows up, it is deployed on staging by tagging it (Note: Not sure how we differentiate containers built of master and from PR's or branches).

@kuisathaverat As usual, would like to get your feedback on the above.

**Comment by kuisathaverat** [comment]
To use the `staging` tag make the update of the package-registry easy, you only need to restart the pod/s and you have the new version, however, it has some cons, it is not easy to know which version is exactly deployed. In the time you are making the rolling update to change the version on all your pods, you can not ensure in an easy way which ones have which version (old or new). If you want to make blue-green deployments it would be really odd to have the same tag on both deployments, even do you can make odd blue-green deployments, the same would happen with canary deployments would be really weird. If you plan to track changes on infrastructure in a git repo, if you use the same tag it is not possible at all, to lose track of when a version is deployed make it difficult to track issues. So I would say that due to the criticality of the service we want to make blue-green deployments or even better canary deployments, those deployments will not be compatible to have the same tag for the current deployment and the in-progress deployment, and to have the same tag is error-prone.

**Comment by ruflin** [comment]
Agree that we should be able to track the deployments, especially see what is deployed right now. I wonder if there would be a way that we on our end still update the `staging` tag but then on the deployment side it figures out which other tag correlates to this. On the deployment side the script then makes sure `202004231234-c890763-c1d2c2c` is deployed.

**Comment by kuisathaverat** [comment]
maybe using labels in the pod, but I do not see the difference of adding a label with the real-tag or change the tag, both options need an update of the configuration.

**Comment by ruflin** [comment]
I would assume a script does this config change for us based on the `staging` label? It checks if `staging` still points to the same hash, if it doesn't it will update the config.

**Comment by kuisathaverat** [comment]
yep, kind of. Because of that, I think changing the tag or the label has the same effort.

**Comment by ruflin** [comment]
I think our recent discussion also answers the above: https://github.com/elastic/package-registry/issues/375#issuecomment-621053570

It will always be possible that we create a special docker image tag for a certain tag we already have but that would not be for releases but for users wanting to have a more user friendly name like `v2.4.2`. As we don't support local registries at the moment, I think we can close this discussion here for now and reopen it when we start to support such a feature.
