### ISSUE TITLE
Remove TLS 1.x from default list of supported protocols

### ISSUE THREAD

**Issue by ycombinator** [elastic/package-registry#1249]
* [x] remove TLSv1.0 and TLSv1.1 as default supported protocols in the TLS configuration sections for for Elastic Agent.
* [ ] remove TLSv1.0 as a supported config option entirely, so that only TLSv1.1 could be manually added back into the list of supported protocols.

**Comment by jsoriano** [comment]
> * remove TLSv1.0 and TLSv1.1 as default supported protocols in the TLS configuration sections for for Elastic Agent.

Marking this first point as done. Package Registry relies on Go defaults by default, and Go sets the minimum version by default to 1.2 since Go 1.22.

It would be pending to remove 1.0 as a valid option from here: https://github.com/elastic/package-registry/blob/0e4c38f92f302489d5cd22ef19239529969334de/flags.go#L17

**Comment by jsoriano** [comment]
Removing TLS1.0 from the list of supported protocols in https://github.com/elastic/package-registry/pull/1259.
