### ISSUE TITLE
Change package access path to /package/apache/1.0.1/

### ISSUE THREAD

**Issue by ruflin** [elastic/package-registry#173]
Currently the information about a package is access by `/package/apache-1.0.1/`. I propose to change this to `/package/apache/1.0.1/`. 

Having `/package/apache-1.0.1/` is partially for historical reasons because it mean, the gzip file is directly in the same directory as the package itself. With https://github.com/elastic/package-registry/pull/169 this changes now and the gzip files end up in a different directory.

Having a top level directory for each package name will make it possible to introduce overall package information in `/package/{package-name}/index.json`. It is not something we need today but we have the place for it when we get there.

Also this could simplify some of the code as the separator between package name and version is always `/` and not `-` which could also exist in the package name.

**Comment by ruflin** [comment]
@jfsiii @skh If we go with this change, we should probably also adjust the API on the Kibana side for consistency.

**Comment by jfsiii** [comment]
FWIW, the plan on EPM is to go with `name@version` https://github.com/elastic/kibana/issues/41253 since it gives the same parsing benefits and is the syntax used for [installing dependencies in `npm`](https://docs.npmjs.com/cli/install) & `yarn`

```
npm install <name>@<version>
npm install <name>@<version range>
```

The most important part from EPM's POV is to remove the `-` separator, so `name/version` works as well.

**Comment by ruflin** [comment]
Done in https://github.com/elastic/package-registry/pull/300
