### ISSUE TITLE
Automate PR to change the Docker image deployed in elastic-apps

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/package-registry#213]
We want to automate the changes on the infra repository `package-registry-staging.yaml` to set the new docker image on a new master branch valid commit, the process would be something like:

* A commit is merger on the master
* it passes the whole pipeline (build, test, Docker image)
* We make a PR to the infra repo with the new tag (SHA1), the PR will contain all metadata need to identify the version deployed.
* The PR is reviewed, approved and merged manually

**Comment by kuisathaverat** [comment]
We will do the same but for the `package-registry-prod.yaml` file when a new tag is created.

**Comment by ruflin** [comment]
@kuisathaverat I worry about the last manual part. There might be 5-10 PR's a day in some cases.

**Comment by kuisathaverat** [comment]
>@kuisathaverat I worry about the last manual part. There might be 5-10 PR's a day in some cases.

This is continuous deployment 😄, so yes it could be a little annoying,  then we can use a special tag pattern to promote commits (e.g. stage-20200217)

**Comment by ruflin** [comment]
Yep, I think that is where we end up. Often updates are not related to changes in the registry itself but package changes.

**Comment by JoshMock** [comment]
I do think once it goes to production that it'd be ideal to have the last step be manual, for the sake of security and the ability to audit changes to the project. We can discuss the benefits and drawbacks of that later.

While it's still in development, it should work to run a `kubectl` command from Jenkins to roll out an upgrade to a fresh image:

```bash
PR_ENVIRONMENT=prod # can also be "staging"
PR_NAME=package-registry-$PR_ENVIRONMENT
PR_DEPLOYMENT=deployment.apps/$PR_NAME-vanilla

kubectl --record $PR_DEPLOYMENT \
  set image $PR_DEPLOYMENT \
  $PR_NAME=docker.elastic.co/package-registry:some-tag \
  -n package-registry
```

This will update the image that's used and perform a rolling update to apply it to all the pods without any downtime.

Obviously that requires having the correct GCP credentials configured, but assuming that's done it's a fairly straightforward thing to do.

**Comment by ruflin** [comment]
I had a follow up conversation on the versioning of "tagging" of the docker images. In the future, the packages will go into its own repository but will be combined with the registry when building the docker images. This means we have two versions:

* Release of the packages
* Release of the registry itself

As there is very little code in the registry itself, I expect not many chance on the registry side. The registry itself uses semantic versioning like `1.3.2`. New packages will ship very frequently. As there are many packages, even when only one has a new version, a new docker image is required. To not have constant releases, we could have for example daily releases that we tag with `2020-02-18` or `20200218`. 

Having a container, I think it is important to know for debugging which version of the packages it is and which version of the registry. Because of this we could combine the two as a tag of the docker image:

1. 20200218-1.3.2
2. 1.3.2-20200218

I slightly prefer option 1 as I would argue the package version is more important as most issue will probably be around certain packages and not the registry itself. So this should come first.

On staging I would like to see us doing continues releases and have a tag for it that we update after each merge, something like `master` or `SNAPSHOT` and the registry will automatically update itself.

For master, we should rely on the daily builds. We should have a script do build a daily tag manually and also then trigger the release manually.

**Comment by JoshMock** [comment]
Given this information, I wonder if it would be worthwhile for us to explore adjusting how this is served in elastic-apps. It's possible that we could deploy multiple containers on a single pod that have access to a shared volume so the application container has access to the packages container. Doing that would make it easy to promote each container's version separately.

Alternatively, I'd suggested a while back having packages stored as static assets in a GCP bucket, which the registry application is aware of. Is that something you'd still consider doing, or are there reasons why we might want to avoid it? It would certainly simplify the way the application is hosted from our perspective.

**Comment by ruflin** [comment]
@JoshMock Definitively open for alternative approaches. The current approach will break in the long term but at the same time I want to keep things simple. What I like most about the current approach is that packages + registry are shipped "atomically". So if we have an issue with package + registry, we can pull down one specific container and debug it. No need to figure out what the exact combination was that failed. 

At the moment our main use of the local setup is for development and testing purpose. I guess for this the single Docker container is pretty convenient. In the future I imagine users running their own registry and I think that is where the GCP approach would fall apart?

**Comment by JoshMock** [comment]
>In the future I imagine users running their own registry and I think that is where the GCP approach would fall apart?

That's a good point. The portability of Docker containers is a really valuable selling point for that use case. Given that, it's probably worth exploring the first solution I mentioned, where we set up epr.elastic.co to run as two containers with a shared volume in elastic-apps.

As far as local development is concerned, switching to a two-container solution would be easily solved with `docker-compose`.

**Comment by ruflin** [comment]
What would be the benefit of the two containers besides having separate versions?

**Comment by kuisathaverat** [comment]
From the testing perspective to have only one container is an easier approach, to have two containers on different versions makes that you have to tests every container combination and have a compatibility matrix, I guess not all packages will work with all the versions of the agent (and it make sense).

About to have the packages on some kind of bucket (or whatever shared stored) this makes that you lose the track of the changes and introduces complexity in the test that you have to run because you do not have a unit (unique block indivisible that you can grab) to test against, for example, S3 can track the changes on files but it is not an SCM like git and introduces a new type of system in the whole release process. I always like simple things, they generate fewer headaches.

**Comment by ruflin** [comment]
Lets separate two topics here:

* What we do right now
* What we need for production

What I would like to see right now is that prod and staging deployments will pull new images from our registry instead of docker hub. For this I assume a tag "master" would work. This tag we overwrite every time master is changed and is what we should be pulling today in the script. This will allow me to remove the docker-hub part.

And then follow up on production what we will do there.

**Comment by kuisathaverat** [comment]
I have made a PR to change the image on both files `package-registry-staging.yaml` and `package-registry-prod.yaml`

**Comment by ruflin** [comment]
I have remove all the docker images on Docker hub. We now 100% rely on our own registry.

**Comment by kuisathaverat** [comment]
@ruflin Is anything pending here? I do not think so, I guess we can close it, and open a new one when we have more details about the production release process.

**Comment by ruflin** [comment]
All works as expected. Closing. I will follow up with a new issue related to the release tagging.
