### ISSUE TITLE
Download stats

### ISSUE THREAD

**Issue by ruflin** [elastic/package-registry#31]
To be able to have stats on (unique) downloads for each integration, the integrations registry should support to store download statistics. The stats should be stored in Elasticsearch. The suggested format is as following:

```
{
    "@timestamp": "download-time"
    "integration.name: "apache",
    "integration.version": "1.3.2",
    "source.ip": "149.126.4.81"
}
```

One data point is stored per download. This allows to answer the following question in Elasticsearch:

* Downloads of an integration last 7 days
* Total downloads of an integration
* Total downloads of an integration per version
* Unique downloads of an integration (source.ip)
* Combinations of all the above

**Comment by hbharding** [comment]
This looks great. Some thoughts:

1) We should definitely track `total downloads per version`, but we probably don't want to expose this to the user (or at least not very prominently). If we did, users may feel reluctant to upgrade to the newest package if they saw it had fewer downloads compared to an older version. I think the focus should be on `total downloads per integration`.

2) We may also want to track the usage of an integration's assets. For instance, if an integration ships with 5 dashboards, it may be interesting to know which of those dashboards our users have enabled.

**Comment by ruflin** [comment]
++ on focus on the total downloads at the first. The nice part about the data above is that it gives us all  the possibilities. I would also expose only stat you mentioned to get started through the API.

For point 2: This would mean, the integrations manager would ship back some stats to the registry on what the status of the installation is?

**Comment by hbharding** [comment]
For point 2: Yes, if that's allowed and this information is NOT deemed sensitive :). Just an idea thats probably out of scope for our 1st version and maybe not necessary at all.

But, a simple use case for collecting this type of data: If a particular asset in an integration is getting very little usage (i.e. installs), it may be a signal that we should:
a) remove it, because it's not providing value and it's bloating the integration, which can cause decision fatigue
b) improve it, because it might be lacking a certain feature

There may be other use cases... I can't say whether or not my use case is important enough to justify collecting this information, or if we would actually make use of this data to improve our integrations. Just brainstorming.

**Comment by ruflin** [comment]
Closing for now as in our first version we will not collect these stats in ES.
