### ISSUE TITLE
Add a owner field in the package description

### ISSUE THREAD

**Issue by ph** [elastic/package-registry#451]
Currently it's hard to know which package belongs to which team. It would be nice to be able to know who is responsible for it: Platform, Service or SEIM. We could resolve that by either adding a top-level field `owner` or adding as metadata to the package.

Maybe the later is a better solution  because we do not know how or even if we will surface that to the end user.

cc @ruflin

**Comment by ruflin** [comment]
I've been also thinking about an `author` or `contributors` field that exists in other package managers: https://docs.npmjs.com/files/package.json#people-fields-author-contributors It is a nice way to give "credit" to the creators and allow users to reach out to the. This will become especially relevant if we support community packages.

The two fields overlap in the beginning but might diverge. An author / contributor stays in, an owner might change. I wonder if we could mix the two.

Looking at the Google Play store, they have developer contact with a few fields as an example. We could do something like:

```
contact.website: discuss.*...
contact.github: @elastic/ingest-management
contact.name: ruflin 
contact.email: foo@bar.com
```

Fields are not required but could be filled in and are also part of the package. In our case, we can use it also for tracking the owner based on the Github entry which can be a single user or a group.

Not convinced about the naming yet :-(

**Comment by ph** [comment]
Looking at rubygems which is similar to NodeJS and they do support **author** or **contributors**, I think is a more convenient and future proof to do  it. I can imagine tha author could be "Elastic" and the contributors you and I. I supposed when we open the registry we could have RBAC based on that and give contributors push access.

I would use something similar as this for each entry:

```
website: discuss.*...
source: https://github.com/elastic/...
name: ruflin 
email: foo@bar.com
```

**Comment by ruflin** [comment]
What you mean for each entry? Could you share a full yaml on how it would look like?

**Comment by ph** [comment]
```json
{
  "source": "http://github.com/elastic/mymodule",
  "website": "http://elastic.co",
  "author": {
    "name": "Elasticsearch",
    "email": "info@elastic.co"
  },
  "contributors": [
    {
      "name": "Ruflin",
      "email": "spam@elastic.co"
    },
    {
      "name": "PH",
      "email": "spam@elastic.co"
    }
  ]
}
```

Something like this, but this doesn't solve which team in Elastic own that module?
Do we allow a `_meta` fields for a package which we could use internally for toolings?

**Comment by ruflin** [comment]
I would rather stay away from "magic" in the packages for internal usage. I'm coming back to the `github` part which I think is really powerful here. Lets assume an author can change over time, then we go with:

```
  "source": "http://github.com/elastic/mymodule",
  "website": "http://elastic.co",
  "author": {
    "name": "Elastic",
     "github": "elastic/integrations",
    "email": "info@elastic.co"
  },
```

In most cases, I would not post my email address in public but my github handle. The nice part about a Github handle is it can be a single person or a group. The most compact option we would start with in our package would be:

```
  "author": {
     "github": "elastic/integrations",
  },
```

Can an author change over time? Or should we better go with "owner"? Because this can change over time. I would also it is more relevant as in case of a package, there are potential different authors of each dataset but I would argue only one overall owner (could be a team) of the package.

Based on the above my suggestion would be to start with the following

```
owner.github: "@foo/bar"
```

This allows us to add more fields in the future when requests come up and works for our automation.

**Comment by ruflin** [comment]
I opened https://github.com/elastic/package-registry/pull/536 to move forward with this.

**Comment by ph** [comment]
closing this because https://github.com/elastic/package-registry/pull/536 was merged, OK to do the minimum now.
