### ISSUE TITLE
Encode Kibana dashboards

### ISSUE THREAD

**Issue by mtojek** [elastic/package-registry#466]
The `mage build` step for the package-storage project should encode Kibana dashboards. 

Files in this form will be stored in the package-storage. The package-storage will validate PRs to check if the format is consistent.

**Comment by exekias** [comment]
Would this mean that package-storage dashboards look different than the ones in integrations? What's the reason to do that?

**Comment by mtojek** [comment]
Let me explain starting from the end of the flow.

Kibana accepts objects (dashboards, visualizations, etc.) partially encoded.
The package-registry will not transform or modify any package content (no `mage build` anymore).
The package-storage will only validate package content (check if dashboards are partially encoded).
Here we come to the Integrations repository. We can either keep there Kibana files in the same form, encoded JSON for some fields, or decode them all. If we decode some structures and Git-version them, it's easier to review JSON files.

Actually, this is up to the Integrations team to choose between readability and consistency and decide which one fits better.

**Comment by jsoriano** [comment]
> The reason why I do not care much about having decoded dashboards is that we've never edited them manually, in 98% cases we edit them using Kibana designer. This 2% covers small fixes, typos, etc. In general the structure of a dashboard is a mystery (all meta properties, doubled fields, etc.). Even if I edit the dashboard manually, I still have to import it to Kibana to verify.

In beats we have experienced both worlds, dashboards were not decoded first, and since some time ago we decode them (https://github.com/elastic/beats/pull/7224). In my opinion this was an important improvement in dashboards maintenance. Specially because it made much easier or even possible to make small fixes and to review small and not so small changes. Also because it makes the mysterious structure of the dashboards much more approachable :)

Something similar happened with pipelines, originally we had all of them in JSON, and supporting yaml (https://github.com/elastic/beats/pull/11209) was a big improvement for developing and reviewing some of the more complex ones. Elasticsearch only supports pipelines in JSON format, but we use yaml for development, and the tooling (filebeat setup in this case) takes care of the conversions. By the way, what takes care of converting pipelines from yaml to json in packages?

> I do not insist on this approach, I can live with decoded objects for sure :)

I'd want to remark that my point is not only about decoded vs encoded objects, it is also that I think that having a build step doesn't look unexpected, and we are probably going to need it in any case at some moment. And given that, why doing sacrifices in maintainability?

> * During daily development and maintenance a developer would need to run `build` step every time, they would like to reflect changes to a format compatible with package-registry.

I will be surprised if we don't find more reasons to need a `build` step. I think that served packages don't need to be the same as their source files (as happens with any other packaging system I can think about). I wouldn't count on this as an advantage of not having decoded dashboards :)

> * In the future we plan to have an automation that can move updated integrations to the package-storage. This mechanism will have to build the integration first, then copy outputed contents.

But (hopefuly) the integrations repository is not going to be the only source of packages in the future. If some day we have packages from more repositories, or we open the registry to external contributions, we will need a way to prepare the files to be served, this could be a task for `elastic-package build`, and it could take care of doing any needed conversion.
Also if we implement different backends for the package registry, we will probably need an agnostic way of generating the package files from its source files.

**Comment by mtojek** [comment]
Thanks Jaime, it's good justification. I wasn't aware of all historical reasons.

> By the way, what takes care of converting pipelines from yaml to json in packages?

I think they're both supported by Kibana.

> I will be surprised if we don't find more reasons to need a build step.

At the moment, it looks so, but I'm not sure if it evolves in the future ;) My point was to get closer to static files as much as possible, even by eliminating `mage build` at all. I wouldn't like to support two formats (encoded and decoded) by the Package Registry if it's not required.

I will modify CM steps to keep dashboards decoded in the integrations repository.

**Comment by ruflin** [comment]
@jsoriano ES supports JSON and YAML pipeline. It basically supports YAML for everything, just the Beats code didn't ;-)

**Comment by mtojek** [comment]
Everything is merged, CM is finished.

Thanks everyone for discussion. Resolving.
