### ISSUE TITLE
Return packages of all stabilities by default?

### ISSUE THREAD

**Issue by ycombinator** [elastic/package-registry#596]
Right now, the package registry's search API does not return packages marked as `experimental` stability unless `?experimental=true` is set. I don't know the history behind this decision so I want to raise this as a discussion first.

Would it make sense to change the default behavior of the search API to return packages of all stabilities, especially considering that most packages are marked as `experimental` for now? The client can always decide to not request experimental packages by sending `?experimental=false` then.

**Comment by ph** [comment]
I would be OK to return all by default and make the stability an explicit filter.

**Comment by ruflin** [comment]
The initial assumption was that most users are not interested in experimental packages and the default behaviour should exclude them. This now changes as most of the packages are experimental. So short term this assumption is wrong but I would hope long term it still holds.

The API behaviour should not change as otherwise it is a breaking change. So if we assume long term the experimental packages should not be shown by default, I would keep it as is and pass a flag from Kibana instead. If we want to show always also experimental packages by default, lest change it.

One thing to note is that this will long term not only affect Kibana but for example also the Website and list of packages.

**Comment by ycombinator** [comment]
Thanks @ruflin. I did not realize the API was public and GA already so breaking changes were not possible already. At any rate, I agree with taking the long-term view. Hopefully in a few months we're going to start seeing fewer and fewer experimental packages.

**Comment by ruflin** [comment]
@ycombinator We can still do a breaking change until 7.9 is shipped :-)

**Comment by ycombinator** [comment]
Cool, but still I agree with you that we should take the long-term view here. Just because the majority of packages are experimental today doesn't mean that will be the case for very long (hopefully!). And if so, hiding experimental packages by default in the API response seems like the right design.

**Comment by ruflin** [comment]
@ph You might be able to chime in here an update on what changes we made to Kibana so far?

**Comment by ruflin** [comment]
As moving forward I expect by default we will not show the experimental packages anymore, I'm going to close this as we keep the current default. Please reopen @ycombinator if you see it differently.
