### ISSUE TITLE
Use the package-spec for validation

### ISSUE THREAD

**Issue by ruflin** [elastic/package-registry#626]
Currently the package registry has quite a bit of code around package validation. Moving forward most of the validation should rely on elastic-package code instead: https://github.com/elastic/elastic-package

**Comment by ruflin** [comment]
@ycombinator Could you confirm if the above makes sense?

**Comment by ycombinator** [comment]
Under the hood, `elastic-package` depends on the golang library provided by `package-spec` for validating packages. See:
* https://github.com/elastic/elastic-package/blob/4571f45c28540f8de33a8d842f4f8fb527020486/cmd/lint.go#L30,
* https://github.com/elastic/elastic-package/blob/4571f45c28540f8de33a8d842f4f8fb527020486/cmd/lint.go#L4, and
* https://github.com/elastic/elastic-package/blob/4571f45c28540f8de33a8d842f4f8fb527020486/go.mod#L8

So I'm wondering if it makes sense for the package registry code to similarly depend directly on the same golang library instead of depending on `elastic-package`?

**Comment by ruflin** [comment]
SGTM

**Comment by jlind23** [comment]
[Clean up] Closing this as outdated, will reopen if required.
