### ISSUE TITLE
Disable integration tests for Package Registry

### ISSUE THREAD

**Issue by mtojek** [elastic/package-registry#698]
There are contract tests present and enabled in the repository, so it seems that we don't need to keep integration tests against the whole stack (Kibana, Fleet, etc.). Let's disable them.

**Comment by ruflin** [comment]
What is the concern here? Are these flaky? Taking too long?

**Comment by mtojek** [comment]
Please take a look at reference thread with @jsoriano and @v1v.

Long story short - we're looking for opportunities to simplify updating references to  Elastic stack images. In this case integration tests against Kibana don't give anything much value as we have API contract tests.

**Comment by ruflin** [comment]
Got it, thanks for the details. I'm hesitant to fully remove the tests as I think it still provides some value. A dev opening a PR against the repo will see on the PR itself that something is not working instead of seeing it only later through e2e tests or similar.

Let me propose an alternative. In general we are pretty good in testing the "current" version but sometimes lack on testing against older version. We know the oldest version that the package registry should work with is 7.10 (please double check) so this is the version we always test against. If we break one of the version that are currently under development, I'm pretty sure we will quickly know because of all the other test systems.

**Comment by mtojek** [comment]
> Got it, thanks for the details. I'm hesitant to fully remove the tests as I think it still provides some value. A dev opening a PR against the repo will see on the PR itself that something is not working instead of seeing it only later through e2e tests or similar.

With this file we have covered all endpoints and, I think, edge cases: https://github.com/elastic/package-registry/blob/master/main_test.go . If a dev opens a PR against this repo, one of these contract tests would fail when the response body is different.

> Let me propose an alternative. In general we are pretty good in testing the "current" version but sometimes lack on testing against older version. We know the oldest version that the package registry should work with is 7.10 (please double check) so this is the version we always test against.

Do you think that there is an edge case which won't be caught with contract tests, but might be possible to catch with legacy testing? Personally I consider contract tests sacred and this is the first "blocker" for any changes in API. Keep in mind that package-registry doesn't keep any state or logic which can modify its behavior.

cc @jsoriano

**Comment by jsoriano** [comment]
>> In this case integration tests against Kibana don't give anything much value as we have API contract tests.

> I'm hesitant to fully remove the tests as I think it still provides some value.

@ruflin I agree that these tests provide value, so tests like this should exist, but not in this repository. Tests in this repository should be focused on ensuring that the APIs (and their behaviours) don't unexpectedly change.

package-registry doesn't depend on Kibana or Fleet, so there is no technical reason to run integration tests using it. Any integration test is time consuming, a source of flakiness and an extra thing to maintain, so the less, the better. Apart of that, we could be testing a subset of the features of Kibana that is not real, Kibana could add a new use of the registry and integration tests in the package registry wouldn't be covering it, till explicitly added. It would be similar if Elasticsearch had integration tests with Kibana, Beats, Logstash or any other client, they would probably be a burden for the Elasticsearch team, while eventually not covering the real cases.

These kind of integration tests fit better in the client application, where the use cases are known.

Out of purely technical reasons, Kibana is the main client of the registry, and we have full interest for this integration to be smooth, but for that I see two better methods:
* Ensuring that Kibana is properly testing the components that depend on the registry (I assume that is is already happening), we can of course help here if the registry or its API have some problem to be used in client tests.
* Optionally, adding [E2E tests](https://github.com/elastic/e2e-testing) to cover use cases, possibly with different versions.

**Comment by mtojek** [comment]
I think I agree with most of the post you've written, Jaime. Thanks!

> Optionally, adding E2E tests to cover use cases, possibly with different versions.

This is a good idea, but I would delay it in time as e2e-tests are too much flaky now and builds will be flashing red on daily basis.

**Comment by jsoriano** [comment]
>> Optionally, adding E2E tests to cover use cases, possibly with different versions.
>
> This is a good idea, but I would delay it in time as e2e-tests are too much flaky now and builds will be flashing red on daily basis.

Well, there is selective testing there, but I agree that this can be left for later if needed. In principle it should be enough with contract testing in the registry and the tests that Kibana/Fleet do, but in the future we may want to have some suite to validate that we don't break support with older versions that users may be still using.

**Comment by ruflin** [comment]
Thanks for the additional thoughts. I think we are aligned that we need the tests but not necessarily as part of the package-registry. 

The part I'm most worried about is that by accident we might break older version of Kibana which Kibana does not test anymore. Lets say we add a field "foo:bar" to one of the outputs. In theory, this should not be a breaking change but maybe an older version of Kibana does iterate through the fields instead of taking the key directly (made up example of course). Now we merge and deploy this change and unknowingly we broke all deployments of with this older version of Kibana. These multi version compatilbility tests are likely to be best run in e2e or an other repo as it does not only include the package-registry but is more specific to the package registry distributions with the packages.

I'm good with moving forward on this.
