### ISSUE TITLE
Support EPR distribution as a Containerd image

### ISSUE THREAD

**Issue by akshay-saraswat** [elastic/package-registry#725]
EPR is provided as a Docker image for Elastic customers to host it in an air-gapped environment. Since Docker is not free for businesses anymore, Containerd runtime environment is becoming more popular. Our customers would prefer and benefit more from a Containerd image of the EPR instead of a Docker image.

**Comment by jsoriano** [comment]
Hey @akshay-saraswat,

In principle Docker images are OCI-compatible and can be executed by different runtimes. Also, our docker images are served through `docker.elastic.co`, not through the docker hub, so in principle no Docker technology needs to be used to run the registry.

For example the following command works:
```
podman run -it --rm docker.elastic.co/package-registry/distribution:production
```
(podman is an Apache-licensed container runtime https://github.com/containers/podman)

So I don't think any action needs to be taken regarding image building (as long as images built with docker are compatible with other OCI-compliant runtimes).

Should we update the documentation mentioning that other runtimes can be used instead of docker?

**Comment by jsoriano** [comment]
Update. It also works with containerd itself:
```
sudo ctr images pull docker.elastic.co/package-registry/distribution:production
sudo ctr run -t --rm docker.elastic.co/package-registry/distribution:production registry
```

**Comment by jlind23** [comment]
@akshay-saraswat could you please check back with customers in order to be sure that everything is working fine.

**Comment by jlind23** [comment]
@akshay-saraswat any update so far?
